apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-supabase-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Stijn-van-Nieulande/nixs-dev-platform.git
        revision: HEAD
        directories:
          - path: "supabase/environments/*"
  template:
    metadata:
      name: "supabase-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Stijn-van-Nieulande/nixs-dev-platform.git
        targetRevision: HEAD
        path: supabase/charts/supabase-wrapper # use the wrapper chart in this repo
        # helm:
        #   valueFiles:
        #     - "../../environments/{{path.basename}}/values.yaml" # relative to the chart path
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}" # creates namespace per environment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      # instruct ArgoCD to ignore replica differences (so we can scale pods to zero from external)
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/replicas
  templatePatch: |
    spec:
      source:
        helm:
          valueFiles:
            - "../../environments/{{path.basename}}/values.yaml"
