supabase:
  secret:
    name: supabase-secrets-test-env
    jwt:
      secretRef: "supabase-secrets-test-env"
    db:
      secretRef: "supabase-secrets-test-env"
    analytics:
      secretRef: "supabase-secrets-test-env"
    smtp:
      secretRef: "supabase-secrets-test-env"
    dashboard:
      secretRef: "supabase-secrets-test-env"
    realtime:
      secretRef: "supabase-secrets-test-env"
    meta:
      secretRef: "supabase-secrets-test-env"
  studio:
    environment:
      DEFAULT_ORGANIZATION_NAME: NIXS Entertainment
      DEFAULT_PROJECT_NAME: Slide
      SUPABASE_PUBLIC_URL: http://supabase.test-domain.ndev.stijndevelopment.nl
  auth:
    environment:
      API_EXTERNAL_URL: http://supabase.test-domain.ndev.stijndevelopment.nl
      GOTRUE_SITE_URL: http://supabase.test-domain.ndev.stijndevelopment.nl
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@supabase.test-domain.ndev.stijndevelopment.nl"
      GOTRUE_SMTP_HOST: "smtp.supabase.test-domain.ndev.stijndevelopment.nl"
      GOTRUE_SMTP_PORT: "587"
      GOTRUE_SMTP_SENDER_NAME: "your-mail@supabase.test-domain.ndev.stijndevelopment.nl"
  kong:
    ingress:
      hosts:
        - host: supabase.test-domain.ndev.stijndevelopment.nl
          paths:
            - path: /
              pathType: Prefix
# ------------------------------
labels:
  owner: test owner
  ticket: PT-184
app:
  branch: main
  domain: test-domain
