    
supabase:
  secret:
    name: "supabase-secrets-testie"
    jwt:
      secretRef: "supabase-secrets-testie"
    db:
      secretRef: "supabase-secrets-testie"
    analytics:
      secretRef: "supabase-secrets-testie"
    smtp:
      secretRef: "supabase-secrets-testie"
    dashboard:
      secretRef: ""
      username: "test"
      password: "test"
      openAiApiKey: "super_secret_key"
    realtime:
      secretRef: "supabase-secrets-testie"
    meta:
      secretRef: "supabase-secrets-testie"
  studio:
    environment:
      DEFAULT_ORGANIZATION_NAME: "NIXS Entertainment"
      DEFAULT_PROJECT_NAME: "Slide"
      SUPABASE_PUBLIC_URL: "https://supabase.testje.ndev.stijndevelopment.nl"
  auth:
    environment:
      API_EXTERNAL_URL: "https://supabase.testje.ndev.stijndevelopment.nl"
      GOTRUE_SITE_URL: "https://supabase.testje.ndev.stijndevelopment.nl"
      GOTRUE_URI_ALLOW_LIST: "https://supabase.testje.ndev.stijndevelopment.nl"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@supabase.testje.ndev.stijndevelopment.nl"
      GOTRUE_SMTP_HOST: "smtp.supabase.testje.ndev.stijndevelopment.nl"
      GOTRUE_SMTP_PORT: "587"
      GOTRUE_SMTP_SENDER_NAME: "your-mail@supabase.testje.ndev.stijndevelopment.nl"
  kong:
    ingress:
      tls:
        - secretName: "supabase-tls-testie"
          hosts:
            - "supabase.testje.ndev.stijndevelopment.nl"
      hosts:
        - host: "supabase.testje.ndev.stijndevelopment.nl"
          paths:
            - path: /
              pathType: Prefix
# ------------------------------
authentik:
  kongClientSecretName: "kong-authentik-client-testie"
  kongClientId: "AI1fUNP6D8MUwk25L6ugg8FBscoMapDjrDBhjz6h"
kong:
  oidcPluginName: kong-oidc-testie# ------------------------------
labels:
  owner: "Stijn"
  ticket: ""
app:
  branch: "main"
  domain: "testje"
