apiVersion: v2
name: supabase-wrapper
description: "Wrapper chart to deploy Supabase and run PostSync Job to apply functions from backend repo"
version: 0.2.0
type: application
dependencies:
  - name: supabase
    version: "0.2.0"
    repository: "oci://harbor.ndev.stijndevelopment.nl/library"
    # repository: "https://github.com/supabase-community/supabase-kubernetes"
